import os
from dotenv import load_dotenv

load_dotenv()

# API Configuration
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

# Difficulty Presets
DIFFICULTY_PRESETS = {
    'easy_focused': {'easy': 60, 'medium': 30, 'hard': 10},
    'balanced': {'easy': 40, 'medium': 40, 'hard': 20},
    'moderate': {'easy': 30, 'medium': 50, 'hard': 20},
    'hard_focused': {'easy': 20, 'medium': 40, 'hard': 40},
    'competitive': {'easy': 10, 'medium': 40, 'hard': 50}
}

# Base Templates
HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>VisionWire AI Study Pack</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #6e8efb, #a777e3); color: white; padding: 30px; text-align: center; border-radius: 10px; margin-bottom: 30px; }}
        h1 {{ margin: 0; }}
        h2 {{ color: #2c3e50; border-bottom: 2px solid #6e8efb; padding-bottom: 10px; }}
        .section {{ margin-bottom: 40px; background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }}
        .mcq-item {{ margin-bottom: 15px; padding: 10px; border-left: 4px solid #6e8efb; }}
        .options {{ list-style-type: none; padding-left: 0; }}
        .option {{ margin: 5px 0; }}
        .footer {{ text-align: center; font-size: 0.8em; color: #777; margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>VisionWire AI Study Pack</h1>
        <p>{class_level} | {exam} | {subject} | {chapter}</p>
    </div>
    
    <div class="section">
        <h2>Summary</h2>
        <div>{content_summary}</div>
    </div>
    
    <div class="section">
        <h2>Important Points</h2>
        <ul>{important_points}</ul>
    </div>
    
    <div class="section">
        <h2>Practice Questions (MCQs)</h2>
        <div>{mcqs}</div>
    </div>
    
    <div class="footer">
        Generated by VisionWire AI - हर बच्चे का अपना AI Tutor 🎓
    </div>
</body>
</html>
"""
